### ISSUE TITLE
Errors when downloading dependencies

### ISSUE THREAD

**Issue by alhimik45** [vladh/lein-sassy#1]
I writed in project.clj
```clojure
  :plugins [[lein-sassy "1.0.1"]]
```
Then wrote `lein deps` but got error:
```
Could not find artifact org.rubygems:haml:jar:3.1.7 in central (http://repo1.maven.org/maven2/)
Could not find artifact org.rubygems:haml:jar:3.1.7 in clojars (https://clojars.org/repo/)
Could not find artifact org.rubygems:haml:jar:3.1.7 in gem-jars (http://gemjars.org/maven)
Could not find artifact org.rubygems:haml:jar:3.1.7 in torquebox (http://rubygems-proxy.torquebox.org/releases)
Could not find artifact org.rubygems:sass:jar:3.2.1 in central (http://repo1.maven.org/maven2/)
Could not find artifact org.rubygems:sass:jar:3.2.1 in clojars (https://clojars.org/repo/)
Could not find artifact org.rubygems:sass:jar:3.2.1 in gem-jars (http://gemjars.org/maven)
Could not find artifact org.rubygems:sass:jar:3.2.1 in torquebox (http://rubygems-proxy.torquebox.org/releases)
```

**Comment by vladh** [comment]
Hi, could you please post your project.clj? You seem to be getting errors with haml which is weird since this plugin doesn't use it.

**Comment by alhimik45** [comment]
Here is full project.clj:
```clojure
(defproject sass-example "0.1.0"
  :dependencies [[org.clojure/clojure "1.6.0"]]
  :plugins [[lein-sassy "1.0.1"]]
  :sass {:src "src-sass" 
         :dst "static"})
```

**Comment by vladh** [comment]
Can you please try again with version 1.0.2? I had put the wrong gemjars URL in there, that's why it wasn't working. Sorry about that!

**Comment by alhimik45** [comment]
Hm, now it gives exception:
```
java.lang.RuntimeException: No such var: lmain/warn, compiling:(leiningen/lein_sassy/options.clj:14:5)
```

**Comment by vladh** [comment]
That's a function from [here](https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/main.clj). Do you have the latest version of Leiningen?

**Comment by alhimik45** [comment]
Yes, I upgraded lein, but now it gives me many syntax error although that the file is valid and compiles by [lein-sass](https://github.com/101loops/lein-sass). Here is example project [link](https://drive.google.com/file/d/0Bz7Myw57yQvoNmZXMnl0aW1uSVk/view?usp=sharing)

**Comment by vladh** [comment]
The problem seems to be that `@import` can't find the files to import — your files, compiled separately, work fine for me. I'm looking into the `@import` issue now, probably just a wrong path somewhere.

**Comment by vladh** [comment]
Also, you need to make sure that you are using the syntax without braces. It is possible to enable the one with braces as a project.clj option.

**Comment by vladh** [comment]
I fixed a bunch of issues with partials, can you please try everything again and tell me if it works fine? Thanks!

**Comment by alhimik45** [comment]
Yes, it compiles, but partials also compiles into css files, what shouldn't be(http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials)

**Comment by vladh** [comment]
Are you sure it also does that with the latest version, and after clearing the output directory?

**Comment by alhimik45** [comment]
Ohh, sorry, I didn't clean output directory. All works ok.

**Comment by vladh** [comment]
Great, I'm glad to hear that!
