### ISSUE TITLE
Missing release

### ISSUE THREAD

**Issue by matthiasn** [vladh/lein-sassy#14]
Hi, thanks for this project, it's been working well for me for months.

Today, though, I had the dubious pleasure of installing some software of mine on windows and the output path didn't work, as described in issue #6. When I installed the plugin locally with `lein install`, everything worked fine, so I assume the released version 1.0.7 does not contain that PR. 

Can you please release a new version that includes the fix?

Cheers,
Matthias

**Comment by vladh** [comment]
Hey Matthias, thanks for the kind words. Sorry for not making a release. I'll do that as soon as I'm back from vacation next week. I hope that's okay for you. Sorry for not being able to do it sooner.

**Comment by matthiasn** [comment]
Sure that's great, thanks!

**Comment by vladh** [comment]
I've published a new version, can you verify that it works now?

**Comment by matthiasn** [comment]
Hi Vlad, great, thanks! I'll check tomorrow when I'm near a Windows machine. Cheers, M

**Comment by matthiasn** [comment]
Yes, working fine now. Thank you
