### ISSUE TITLE
Can't find jruby 1.7.16

### ISSUE THREAD

**Issue by tuhlmann** [vladh/lein-sassy#3]
Sorry to report,

just installed lein-sassy 1.0.5 and did a `lein sass once` which gives the following error:

```
Retrieving lein-sassy/lein-sassy/1.0.5/lein-sassy-1.0.5.jar from clojars
Could not transfer artifact org.jruby:jruby-complete:jar:1.7.16 from/to central (https://repo1.maven.org/maven2/): Read timed out
Could not find artifact org.jruby:jruby-complete:jar:1.7.16 in clojars (https://clojars.org/repo/)
```

Torsten.

**Comment by tuhlmann** [comment]
Uh, forget that comment please.
I just issued the command again then succeeded. The only difference I see is that the lein-sassy plugin was already downloaded that second step...

Compilation works now.

Many thanks,
Torsten.

**Comment by vladh** [comment]
Ruby tends to be very fussy, sorry about that.
