### ISSUE TITLE
Not release new version 1.0.6 yet?

### ISSUE THREAD

**Issue by federkasten** [vladh/lein-sassy#7]
However lein-sassy has added some useful functions with #4 and #5, not released a new version 1.0.6 yet.

I think `lein sass clean` and leiningen hooks are very convenient functions.

I hope you release a new version :)

**Comment by vladh** [comment]
You are right, thank you for mentioning this. I will release it tonight (Europe time).

**Comment by federkasten** [comment]
Thanks!

**Comment by vladh** [comment]
[Done!](https://clojars.org/lein-sassy) Thanks again for reminding me!

**Comment by federkasten** [comment]
:+1:
